package com.aisdlc.service;

import com.aisdlc.model.ImplementationPlan;
import com.aisdlc.model.ImplementationStep;
import org.springframework.stereotype.Service;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Set;

@Service
public class ImplementationPlanValidator {

    private final Path repositoryRoot;

    private static final Set<String> VALID_ACTIONS =
            Set.of("MODIFY", "CREATE", "DELETE");

    private static final Set<String> VALID_LAYERS =
            Set.of("BACKEND", "FRONTEND", "DATABASE", "TEST");

    public ImplementationPlanValidator() {

        // ai-sdlc-orchestrator is inside crud-employee
        this.repositoryRoot = Paths.get("..")
                .toAbsolutePath()
                .normalize();
    }

    public ImplementationPlan validate(
            ImplementationPlan plan) {

        if (plan == null) {
            throw new IllegalStateException(
                    "AI generated an empty implementation plan."
            );
        }

        if (!plan.requiresHumanApproval()) {
            throw new IllegalStateException(
                    "Implementation plan must require human approval."
            );
        }

        if (plan.steps() == null || plan.steps().isEmpty()) {
            throw new IllegalStateException(
                    "Implementation plan contains no steps."
            );
        }

        for (ImplementationStep step : plan.steps()) {
            validateStep(step);
        }

        return plan;
    }

    private void validateStep(ImplementationStep step) {

        if (step == null) {
            throw new IllegalStateException(
                    "Implementation plan contains a null step."
            );
        }

        if (step.filePath() == null
                || step.filePath().isBlank()) {

            throw new IllegalStateException(
                    "Implementation step has no file path."
            );
        }

        String action =
                step.action() == null
                        ? ""
                        : step.action()
                              .trim()
                              .toUpperCase();

        String layer =
                step.layer() == null
                        ? ""
                        : step.layer()
                              .trim()
                              .toUpperCase();

        // Validate action
        if (!VALID_ACTIONS.contains(action)) {

            throw new IllegalStateException(
                    "Invalid action from AI: "
                            + step.action()
            );
        }

        // Validate layer
        if (!VALID_LAYERS.contains(layer)) {

            throw new IllegalStateException(
                    "Invalid layer from AI: "
                            + step.layer()
            );
        }

        Path resolvedPath =
                repositoryRoot
                        .resolve(step.filePath())
                        .normalize();

        // Prevent ../ path traversal
        if (!resolvedPath.startsWith(repositoryRoot)) {

            throw new IllegalStateException(
                    "Unsafe file path generated by AI: "
                            + step.filePath()
            );
        }

        // MODIFY and DELETE require an existing file
        if (action.equals("MODIFY")
                || action.equals("DELETE")) {

            if (!Files.isRegularFile(resolvedPath)) {

                throw new IllegalStateException(
                        "AI generated non-existing file for "
                                + action
                                + ": "
                                + step.filePath()
                );
            }
        }

        // CREATE should NOT overwrite an existing file
        if (action.equals("CREATE")) {

            if (Files.exists(resolvedPath)) {

                throw new IllegalStateException(
                        "AI tried to CREATE an existing file: "
                                + step.filePath()
                );
            }
        }
    }
}